### ISSUE TITLE
Dynamic Resizing of Hierarchy Windows

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#233]
Module: Impact Assessment
Page: Impact Assessment

Dynamic resizing of heirarchy windows does not work on varying screen resolution. 

Default:
![image](https://cloud.githubusercontent.com/assets/12534580/25005316/697972bc-2026-11e7-8b2d-17a745696cb9.png)

BUG: The table does not extend when the window is expanded:
![image](https://cloud.githubusercontent.com/assets/12534580/25005295/49a2e612-2026-11e7-874a-5c5aeac4ab1e.png)

BUG: Impact Search cannot be narrowed
BUG: When the box is narrowed from the bottom, it covers/hides the Add Selected button
BUG: Hierarchy Search can't be narrowed vertically further than this
![image](https://cloud.githubusercontent.com/assets/12534580/25005434/f8590be6-2026-11e7-9680-d8231e47c904.png)

Please fix these issues and test thoroughly so that these windows can be dynamically resized for smaller screens, ALSO please test these fixes on the hierarchy windows on Relations page.

Please test **thoroughly** so that it doesn't break functionality.

**Comment by andmiel81** [comment]
This issue has been updated. Please check and confirm

**Comment by acoughlin** [comment]
Could this be addressed again for Select Lists/SMQs window?

**Comment by andmiel81** [comment]
For Select Lists/SMQs window:
 I just made it smaller when it first opens.
 This dialog must have minimum size, because the tables in the dialg will have 10-rows page and this number of rows per page is fixed, and minimizing the dialog less than certain height will inevitably hide the data itself.
So I propose the current solution: giving the dialog minimum possible initial size( which will fit most of the screen sizes even smaller than 800*600 ) and then making it available for expanding.

**Comment by acoughlin** [comment]
Issue persists, but is low priority

![image](https://user-images.githubusercontent.com/12534580/31667654-17405368-b31e-11e7-88f2-8abbc9738432.png)
